# Generated by Django 3.0.6 on 2020-05-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.CharField(max_length=200)),
                ('de', models.CharField(max_length=200)),
                ('ru', models.CharField(max_length=200)),
                ('ro', models.CharField(max_length=200)),
                ('confidence', models.CharField(choices=[('Sure', 'sure'), ('Maybe', 'maybe'), ('Junk', 'junk')], max_length=50)),
            ],
        ),
    ]
